export const ADD_NEW_MEMO_PENDING = 'ADD_NEW_MEMO_PENDING';
export const ADD_NEW_MEMO_SUCCESS = 'ADD_NEW_MEMO_SUCCESS';
export const ADD_NEW_MEMO_FAILURE = 'ADD_NEW_MEMO_FAILURE';
 
export const DEL_MEMO_PENDING = 'DEL_MEMO_PENDING';
export const DEL_MEMO_SUCCESS = 'DEL_MEMO_SUCCESS';
export const DEL_MEMO_FAILURE = 'DEL_MEMO_FAILURE';

export const GET_MEMO_LIST_SUCCESS = 'GET_MEMO_LIST_SUCCESS';
export const GET_MEMO_LIST_FAILURE = 'GET_MEMO_LIST_FAILURE';